const ENV_VAR = process.env.PUBLIC_URL;

const GENERAL_ROUTE = 'GENERAL_ROUTE';
const PRIVATE_ROUTE = 'PRIVATE_ROUTE';
const PUBLIC_ROUTE = 'PUBLIC_ROUTE';

export {
  ENV_VAR,
  GENERAL_ROUTE,
  PRIVATE_ROUTE,
  PUBLIC_ROUTE,
}